language: go

before_script:
  - go get -u golang.org/x/tools/cmd/vet
  - go get -u golang.org/x/lint/golint
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/axw/gocov/gocov
  - go get -u github.com/mattn/goveralls
  
go: 1.5

script:
  - go build -v ./...
  - go test -v ./...
  - golint ./..
  - go vet ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN

