language: go

before_script:
  - go get -u golang.org/x/tools/cmd/vet
  - go get -u github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  
go: 1.5

script:
  - go build -v ./...
  - go test -v ./...
  - golint ./..
  - go vet ./...
  - go test -v -covermode=count -coverprofile=coverage.out $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
